project_id = "kxwickileuubtyxtuado"

[functions.dda-gis-proxy]
verify_jwt = false

[functions.dld-status-proxy]
verify_jwt = false

[functions.sheets-proxy]
verify_jwt = false

[functions.parse-area-research]
verify_jwt = false